### ISSUE TITLE
Failed to resolve: com.github.amlcurran.showcaseview:library:5.4.0

### ISSUE THREAD

**Issue by priyankvex** [BuildmLearn/Mobile-applications#7]
I was trying to build the project after taking fresh pull and following error has risen.
The showcase library is not getting resolved. 
I tried adding other dependencies but they worked fine.
I also tried adding this library on a fresh project, it failed there too.
I guess there might be some issue with the library.

Can anyone try building the project and validate this?

**Comment by souljaboy764** [comment]
@priyankvex Try building it now. The changes weren't committed after removing the ShowcaseView Library.

**Comment by priyankvex** [comment]
@souljaboy764 It built successfully now.

**Comment by priyankvex** [comment]
Closing the issue.
